["protostar.config"]
protostar_version = "0.2.5"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
a_token = [
    "contracts/protocol/a_token.cairo",
]
pool = [
    "contracts/protocol/pool.cairo",
]

["protostar.shared_command_configs"]
cairo_path = ["./lib/cairo_contracts/src"]
